#ifndef GNURADIO_GLSL2WGSL_HPP
#define GNURADIO_GLSL2WGSL_HPP

#include <regex>
#include <string>
#include <string_view>

namespace gr::device {

/**
 * @brief Minimal GLSL compute shader → WGSL translator.
 *
 * Handles the restricted subset generated by ShaderFragment/ShaderFusion:
 * - layout declarations → WGSL @group/@binding
 * - gl_GlobalInvocationID → @builtin(global_invocation_id)
 * - GLSL types → WGSL types (uint→u32, float→f32, vec2→vec2<f32>)
 * - #define → const declarations
 *
 * NOT a general-purpose transpiler. Only works with the compute-shader patterns
 * generated by generateElementWiseShader() and fuseShaderFragments().
 */
inline std::string GLSL2WGSL(std::string_view glslSource) {
    std::string src(glslSource);
    std::string wgsl;

    // extract workgroup size from layout(local_size_x = N)
    std::size_t wgSize = 256;
    std::smatch m;
    std::regex  wgRe(R"(layout\s*\(\s*local_size_x\s*=\s*(\d+)\s*\)\s*in\s*;)");
    if (std::regex_search(src, m, wgRe)) {
        wgSize = std::stoul(m[1].str());
    }

    // process line by line
    std::istringstream stream(src);
    std::string        line;

    while (std::getline(stream, line)) {
        // skip #version
        if (line.find("#version") != std::string::npos) {
            continue;
        }

        // skip layout(...) in;
        if (line.find("local_size_x") != std::string::npos) {
            continue;
        }

        // #define NAME VALUE → const NAME: f32 = VALUE;
        if (line.find("#define") != std::string::npos) {
            std::regex  defRe(R"(#define\s+(\w+)\s+(.+))");
            std::smatch dm;
            if (std::regex_search(line, dm, defRe)) {
                wgsl += "const " + dm[1].str() + ": f32 = " + dm[2].str() + ";\n";
            }
            continue;
        }

        // readonly buffer → var<storage, read>
        {
            std::regex  bufRe(R"(layout\s*\(\s*binding\s*=\s*(\d+)\s*\)\s*readonly\s+buffer\s+\w+\s*\{\s*float\s+data\[\];\s*\}\s*(\w+)\s*;)");
            std::smatch bm;
            if (std::regex_search(line, bm, bufRe)) {
                wgsl += "@group(0) @binding(" + bm[1].str() + ") var<storage, read> " + bm[2].str() + ": array<f32>;\n";
                continue;
            }
        }

        // writeonly buffer → var<storage, read_write>
        {
            std::regex  bufRe(R"(layout\s*\(\s*binding\s*=\s*(\d+)\s*\)\s*writeonly\s+buffer\s+\w+\s*\{\s*float\s+data\[\];\s*\}\s*(\w+)\s*;)");
            std::smatch bm;
            if (std::regex_search(line, bm, bufRe)) {
                wgsl += "@group(0) @binding(" + bm[1].str() + ") var<storage, read_write> " + bm[2].str() + ": array<f32>;\n";
                continue;
            }
        }

        // void main() → fn main(@builtin(global_invocation_id) gid: vec3<u32>)
        if (line.find("void main()") != std::string::npos) {
            wgsl += "@compute @workgroup_size(" + std::to_string(wgSize) + ")\n";
            wgsl += "fn main(@builtin(global_invocation_id) gid: vec3<u32>) {\n";
            continue;
        }

        // type replacements
        std::string out = line;

        // gl_GlobalInvocationID.x → gid.x
        {
            std::string from = "gl_GlobalInvocationID.x";
            std::string to   = "gid.x";
            std::size_t pos  = 0;
            while ((pos = out.find(from, pos)) != std::string::npos) {
                out.replace(pos, from.size(), to);
                pos += to.size();
            }
        }

        // uint → u32, float → f32 (whole-word only)
        out = std::regex_replace(out, std::regex(R"(\buint\b)"), "u32");
        out = std::regex_replace(out, std::regex(R"(\bfloat\b)"), "f32");

        // inBuf.data[i] → inBuf[i], outBuf.data[i] → outBuf[i]
        out = std::regex_replace(out, std::regex(R"((\w+)\.data\[)"), "$1[");

        wgsl += out + "\n";
    }

    return wgsl;
}

} // namespace gr::device

#endif // GNURADIO_GLSL2WGSL_HPP
