# Default Restyler Configuration: https://github.com/restyled-io/restyler/blob/main/config/default.yaml
pull_requests: false # Open Restyle PRs?
request_review: none
labels: []

comments: false # Leave comments on the original PR linking to the Restyle PR?

# Set commit statuses on the original PR?
statuses:
  # Red status in the case of differences found
  differences: true
  # Green status in the case of no differences found
  no_differences: true
  # Red status if we encounter errors restyling
  error: true

ignore_labels:
  - restyled-ignore

restylers_version: stable

restylers:
  - clang-format:
      image:
        tag: v18
  - cmake-format
  - prettier-markdown
  - prettier-yaml
  - shellcheck
  - whitespace
  - black
